name: Go

on:
  push:

env:
  GO_VERSION: "1.21"

jobs:
  build:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build
        run: go build -v

      - name: Run the binary
        run: ./nacserv-native -once

      - name: Install lint dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - uses: actions/upload-artifact@v3
        with:
          name: nacserv-native
          path: nacserv-native
          if-no-files-found: error
